### ISSUE TITLE
Worker timeout and service 502 on api/upload/complete call

### ISSUE THREAD

**Issue by savvasdalkitsis** [LibrePhotos/librephotos-docker#104]
The service seems to die when i try to complete an upload. 

backend            | [2023-08-09 12:14:55 +0000] [108] [CRITICAL] WORKER TIMEOUT (pid:170)
backend            | [2023-08-09 12:14:57 +0000] [108] [ERROR] Worker (pid:170) was sent SIGKILL! Perhaps out of memory?
backend            | [2023-08-09 12:14:57 +0000] [182] [INFO] Booting worker with pid: 182

I have checked that the system has enough free ram btw.

Full logs:

```
[2023-08-09 09:14:21 +0000] [108] [INFO] Starting gunicorn 21.2.0
[2023-08-09 09:14:21 +0000] [108] [INFO] Listening at: http://0.0.0.0:8001 (108)
[2023-08-09 09:14:21 +0000] [108] [INFO] Using worker: gevent
[2023-08-09 09:14:21 +0000] [110] [INFO] Booting worker with pid: 110
[2023-08-09 09:14:21 +0000] [111] [INFO] Booting worker with pid: 111
use SECRET_KEY from env
use SECRET_KEY from env
Unauthorized: /api/albums/date/list/
Unauthorized: /api/albums/date/1508/
10:54:07 [Q] INFO Enqueued [DjangORM] 19
Internal Server Error: /api/photos/baf52319d94bbecd131ee440559429b41/summary/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/api/views/photos.py", line 375, in summary
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "/code/api/serializers/photos.py", line 144, in get_photo_summary
    return PhotoSummarySerializer(obj.get()).data
                                  ^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
api.models.photo.Photo.DoesNotExist: Photo matching query does not exist.
Unauthorized: /api/photos/baf52319d94bbecd131ee440559429b41/summary/
Unauthorized: /api/photos/baf52319d94bbecd131ee440559429b41/summary/
Not Found: /api/static/rest_framework/js/ajax-form.js
Not Found: /api/static/rest_framework/css/bootstrap-tweaks.css
Not Found: /api/static/rest_framework/js/bootstrap.min.js
Not Found: /api/static/rest_framework/css/prettify.css
Not Found: /api/static/rest_framework/css/bootstrap.min.css
Not Found: /api/static/rest_framework/css/default.css
Not Found: /api/static/rest_framework/js/default.js
Not Found: /api/static/rest_framework/js/jquery-3.5.1.min.js
Not Found: /api/static/rest_framework/js/csrf.js
Not Found: /api/static/rest_framework/js/prettify-min.js
Unauthorized: /api/user/1/
Unauthorized: /api/user/1/
Unauthorized: /api/user/1/
Unauthorized: /api/user/1/
Unauthorized: /api/user/1/
Unauthorized: /api/user/1/
Unauthorized: /api/user/1/
Unauthorized: /api/user/1/
11:11:43 [Q] INFO Enqueued [DjangORM] 20
Internal Server Error: /api/photos/8e26638d1515b7406abcf14d648440871/summary/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/api/views/photos.py", line 375, in summary
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "/code/api/serializers/photos.py", line 144, in get_photo_summary
    return PhotoSummarySerializer(obj.get()).data
                                  ^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
api.models.photo.Photo.DoesNotExist: Photo matching query does not exist.
11:23:14 [Q] INFO Enqueued [DjangORM] 21
Internal Server Error: /api/photos/269c5a5c84dd91bf2310bc9e1bba367f1/summary/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/api/views/photos.py", line 375, in summary
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "/code/api/serializers/photos.py", line 144, in get_photo_summary
    return PhotoSummarySerializer(obj.get()).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "/code/api/serializers/photos.py", line 82, in get_type
    if obj.main_file.embedded_media.count() > 0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'embedded_media'
Unauthorized: /api/user/1/
Unauthorized: /api/user/1/
Unauthorized: /api/albums/date/list/
Unauthorized: /api/albums/date/1471/
Unauthorized: /api/albums/date/1529/
[2023-08-09 12:05:20 +0000] [108] [CRITICAL] WORKER TIMEOUT (pid:110)
[2023-08-09 12:05:25 +0000] [108] [ERROR] Worker (pid:110) was sent SIGKILL! Perhaps out of memory?
[2023-08-09 12:05:25 +0000] [170] [INFO] Booting worker with pid: 170
use SECRET_KEY from env
[2023-08-09 12:13:12 +0000] [108] [CRITICAL] WORKER TIMEOUT (pid:111)
[2023-08-09 12:13:17 +0000] [108] [ERROR] Worker (pid:111) was sent SIGKILL! Perhaps out of memory?
[2023-08-09 12:13:17 +0000] [176] [INFO] Booting worker with pid: 176
use SECRET_KEY from env
[2023-08-09 12:14:55 +0000] [108] [CRITICAL] WORKER TIMEOUT (pid:170)
[2023-08-09 12:14:57 +0000] [108] [ERROR] Worker (pid:170) was sent SIGKILL! Perhaps out of memory?
[2023-08-09 12:14:57 +0000] [182] [INFO] Booting worker with pid: 182
use SECRET_KEY from env
[2023-08-09 12:17:41 +0000] [108] [CRITICAL] WORKER TIMEOUT (pid:176)
[2023-08-09 12:18:43 +0000] [108] [ERROR] Worker (pid:176) was sent SIGKILL! Perhaps out of memory?
[2023-08-09 12:18:43 +0000] [188] [INFO] Booting worker with pid: 188
use SECRET_KEY from env
[2023-08-09 12:22:40 +0000] [108] [CRITICAL] WORKER TIMEOUT (pid:182)
[2023-08-09 12:23:06 +0000] [108] [ERROR] Worker (pid:182) was sent SIGKILL! Perhaps out of memory?
[2023-08-09 12:23:06 +0000] [194] [INFO] Booting worker with pid: 194
use SECRET_KEY from env
```

**Comment by savvasdalkitsis** [comment]
i will give the next dev build a try and report back

**Comment by savvasdalkitsis** [comment]
latest dev seems to have fixed this
