### ISSUE TITLE
Image could not be loaded

### ISSUE THREAD

**Issue by TU-O0T** [LibrePhotos/librephotos-docker#61]
I follow the docs [https://docs.librephotos.com/1/standard_install/](url) and created stacks.
I upload some photos to try, the LibrePhotos successfully identified the photos, and the face recognition works fine. I also can download the photos from the website. But I can't watch photos online. The Thumbnail and photos can't be loaded online.
![image](https://user-images.githubusercontent.com/110141765/181400856-599908b5-fab0-4eda-8089-1ef5766ac293.png)
![image](https://user-images.githubusercontent.com/110141765/181401557-e8971524-d7c0-4fb4-a156-60314fa707ad.png)

Here are the logs from the container which named backend
`/usr/local/lib/python3.9/dist-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.9/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
01:20:53 Worker rq:worker:559c0400956f425a929a901a10e22f5f: started, version 1.10.1
01:20:53 Subscribing to channel rq:pubsub:559c0400956f425a929a901a10e22f5f
01:20:53 *** Listening on default...
01:20:53 Cleaning registries for queue: default
01:20:53 default: api.apps.build_index() (0c8d3204-e856-48c0-835b-871deb7c6918)
127.0.0.1 - - [2022-07-28 01:20:53] "POST /build/ HTTP/1.1" 200 141 0.047056
01:20:53 default: Job OK (0c8d3204-e856-48c0-835b-871deb7c6918)
01:20:53 Result is kept for 60 seconds
01:20:53 default: api.apps.build_index() (a2d5d2f9-c1dd-4a2a-b5a6-825514df6250)
127.0.0.1 - - [2022-07-28 01:20:53] "POST /build/ HTTP/1.1" 200 141 0.025131
01:20:53 default: Job OK (a2d5d2f9-c1dd-4a2a-b5a6-825514df6250)
01:20:53 Result is kept for 60 seconds
01:20:53 default: api.apps.build_index() (b3c64d1d-300c-4549-b1f0-a86e7c4b0d4a)
127.0.0.1 - - [2022-07-28 01:20:53] "POST /build/ HTTP/1.1" 200 141 0.034289
01:20:53 default: Job OK (b3c64d1d-300c-4549-b1f0-a86e7c4b0d4a)
01:20:53 Result is kept for 60 seconds
Unauthorized: /api/searchtermexamples/
Unauthorized: /api/dirtree/
Unauthorized: /api/albums/date/list/
Not Found: /media/thumbnails_big/5
127.0.0.1 - - [2022-07-28 01:22:19] "POST /search/ HTTP/1.1" 200 171 0.003523
Bad Request: /api/nextcloud/listdir/
Not Found: /api/jobs/
Internal Server Error: /api/nextcloud/listdir/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
  File "/usr/local/lib/python3.9/dist-packages/gevent/_socketcommon.py", line 607, in connect
    raise _SocketError(err, strerror(err))
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f0ebe388520>: Failed to establish a new connection: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='172.26.0.7', port=443): Max retries exceeded with url: /ocs/v1.php/cloud/capabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0ebe388520>: Failed to establish a new connection: [Errno 113] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/nextcloud/views.py", line 21, in get
    nc.login(request.user.nextcloud_username, request.user.nextcloud_app_password)
  File "/usr/local/lib/python3.9/dist-packages/owncloud/owncloud.py", line 362, in login
    self._update_capabilities()
  File "/usr/local/lib/python3.9/dist-packages/owncloud/owncloud.py", line 1930, in _update_capabilities
    res = self._make_ocs_request(
  File "/usr/local/lib/python3.9/dist-packages/owncloud/owncloud.py", line 1787, in _make_ocs_request
    res = self._session.request(method, self.url + path, **attributes)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='172.26.0.7', port=443): Max retries exceeded with url: /ocs/v1.php/cloud/capabilities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0ebe388520>: Failed to establish a new connection: [Errno 113] No route to host'))
Unauthorized: /api/rqavailable/`

I don't know why.I think it's not permission issue because the AI is running and I can download the photos. And I try to set 777 to the folder but it doesn't work. I think the proxy or the redis may have something wrong？I need help beacuse I really need it to manage my photos.

**Comment by derneuere** [comment]
The error message you posted has nothing to do with your image error. It talks about the Nextcloud integration, which should is another issue.

My guess is that the proxy isn't working with your setup. It will probably also log an issue for each image it requested. Fixing the proxy issue will resolve your problem, I think.

**Comment by TU-O0T** [comment]
> The error message you posted has nothing to do with your image error. It talks about the Nextcloud integration, which should is another issue.
> 
> My guess is that the proxy isn't working with your setup. It will probably also log an issue for each image it requested. Fixing the proxy issue will resolve your problem, I think.

Here are the docker-compose.yml
![image](https://user-images.githubusercontent.com/110141765/181521353-f9c63bc6-f356-428e-bebb-43f2def45756.png)
Here are the librephotos.env    （When I install the LibrePhotos，I just edit the file path of my photos.）
![image](https://user-images.githubusercontent.com/110141765/181521601-2cc08f55-344b-447a-bc02-b691a05cc3cf.png)
