### ISSUE TITLE
Scanning in SIngleton container

### ISSUE THREAD

**Issue by N-Schaef** [LibrePhotos/librephotos-docker#68]
Hello,

I've tried to scan the library using the singleton container but did not succeed.
Using the recommended
```
sudo docker exec --user root CONTAINER_NAME python3 /usr/lib/librephotos/backend/manage.py scan
```
I get the following error

```
Traceback (most recent call last):
  File "/usr/lib/librephotos/backend/manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
```

After looking at the install file I saw that it uses another user.
But using
```
docker exec --user librephotos CONTAINER_NAME  python3 /usr/lib/librephotos/backend/manage.py
```
I get the error message

```
Traceback (most recent call last):
  File "/usr/lib/librephotos/backend/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/librephotos/.local/lib/python3.10/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/librephotos/backend/ownphotos/settings.py", line 26, in <module>
    raise NameError("Environnement variable not set :" + envvar)
NameError: Environnement variable not set :SECRET_KEY
```

I also tried loading the env file in `/etc/librephotos/librephotos-backend.env` but it does also not contain the secret key.

Did someone manage to use this functionality in the singleton container yet?

**Comment by derneuere** [comment]
This issue is already fixed.
